---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - include_tasks: errorhandle.yml
  - name: install web server
    apt:
      name: apache2
      state: present
  - name: copy static file
    copy:
      src: mystaticfile
      dest: /home/mohduser