---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - name: Excecute direct linux command
    command: hostname -f
    register: result

  - name: I want to display result
    debug:
      msg: "{{myresult}}"

  - name: install git
    apt:
      name: git
      state: present
      when: myresult.stderr ==""

  - name: install tree
    apt: 
      name: install tree
      state: present
      when: myresult.stderr !=""