---
- hosts: mywebservers
  become: yes
  tasks:
   - name: Install Webserver on ANSIBLE red-hat node
     dnf:
       name: httpd
       state: present
     when: ansible_os_family=="RedHat"
   - name: inatll toolbox on webserver
     dnf:
       name: "{{myredhatserver}}"
       state: present
     when: ansible_os_family=="RedHat"
   - name: install synaptic on ubuntu server
     apt:
       name: "{{myubuntuserver}}"
       status: present
     when: ansible_os_family=="Debian"