---
- hosts: myredhatserver
  become: yes
  tasks:
   - name: Install Webserver on ANSIBLE red-hat node
     dnf:
       name: httpd
       state: present
     when: ansible_os_family=="RedHat"
   - name: inatll toolbox on webserver
     dnf:
       name: toolbox
       state: present
     when: ansible_os_family=="RedHat"
   - name: install synaptic on ubuntu server
     apt:
       name: synaptic
       status: present
     when: ansible_os_family=="Debian"