---
- hosts: all
  become: yes
  tasks: 
   - name: install apache2
     apt: 
        name: apache2
        state: present
   - name: Install git
     apt:
        name: git
        state: present
   - name: install curl
     apt:
        name: curl
        state: present
     when: ansible_os_family == "Debian"
   - name: start apache server web services
     service:
        name: apache2
        state: started
     when: ansible_service_mgr == "systemd"